### ISSUE TITLE
Bug? Process not terminating

### ISSUE THREAD

**Issue by frederikheld** [dbusjs/node-dbus-next#69]
Hey,

if I initialize a system or session bus, the program won't terminate. 

```js
// example.js
'use strict' // happens without strict mode as well

const dbus = require('dbus-next')

const bus = dbus.systemBus() // happens with dbus.sessionBus() as well

```
If I run it on the terminal like this, it will run forever:
```
$ node example.js
```
I have to use <kbd>Strg</kbd>+<kbd>C</kbd> to terminate it.

Those are the versions I'm using:

```
Ubuntu: 20.10
node:  14.16.0
dbus-next: ^0.9.2
```

As I couldn't find any information that dbus needs to be closed/terminated/unset in some way, I assume that this is a bug.

I started to use dbus-next just a couple of days ago (when 0.9.2 was already released) but I still think that I didn't have this issue yesterday :-P But I'm not certain and I have no idea what could have introduced the issue.

Any ideas what's going on here?

Cheers
Fred

**Comment by acrisci** [comment]
The bus runs in the background to process dbus messages. If you want it to stop, use `bus.disconnect()` when you are done with it and the process should terminate.

**Comment by frederikheld** [comment]
Thanks for the quick reply!

I was looking for something like this, but trying it like this

```js
'use strict'

const dbus = require('dbus-next')

const bus = dbus.systemBus()

bus.disconnect()
```

throws 

```
Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at Socket.Writable.write (internal/streams/writable.js:292:11)
    at /home/frederik/dbus-example/node_modules/dbus-next/lib/handshake.js:84:16
    at Socket.readable (/home/frederik/dbus-example/node_modules/dbus-next/lib/readline.js:12:11)
    at Socket.emit (events.js:315:20)
    at emitReadable_ (internal/streams/readable.js:569:12)
    at processTicksAndRejections (internal/process/task_queues.js:79:21)
Emitted 'error' event on MessageBus instance at:
    at EventEmitter.<anonymous> (/home/frederik/dbus-example/node_modules/dbus-next/lib/bus.js:159:12)
    at EventEmitter.emit (events.js:315:20)
    at Socket.<anonymous> (/home/frederik/dbus-example/node_modules/dbus-next/lib/connection.js:86:10)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}
```

It looks like something is still using that bus? But I have literally just reastarted my computer before I tried this and the example is as simple as I posted it here.

Is it intended that the bus is running forever? I haven't found any info on this in your examples.

Cheers
Fred

**Comment by acrisci** [comment]
You've run into the unusual case of disconnecting a bus that hasn't connected yet. That's a bug I need to fix.

> Is it intended that the bus is running forever?

Yes

**Comment by frederikheld** [comment]
:-D okay. So I have to put some sleep in between to fix this :-D

This actually works :-)
```js
'use strict'

const dbus = require('dbus-next')

const bus = dbus.systemBus()

setTimeout(() => {
    bus.disconnect()
}, 1000)
```

If this is intended, you should mention the need for explicitly calling disconnect() in the docs. I couldn't find anything about it in the examples and even the api docs don't say much about the importance of disconnect. For me it is unexpected that it is intended that bus never terminates and thus needs to be terminated explicitly.

But I'm beginning to understand the reasoning behind it and I think my approach of working with the MessageBus is wrong...

**Comment by frederikheld** [comment]
Is this error I just got in any way related to the fact, that dbus-next keeps connections open?

`DBusError: The maximum number of active connections for UID 1000 has been reached`

**Comment by acrisci** [comment]
Creating a bus is a heavyweight operation. You should only have one MessageBus for your whole application.

**Comment by frederikheld** [comment]
So I should declare it a global? I actually expected that `dbus.systemBus()` already is the global that just returns the reference...

Do you know any real application based on `dbus-next` that I could look into to see how others are doing it?

**Comment by acrisci** [comment]
This library was originally written for [mpris-service](https://github.com/dbusjs/mpris-service). The test suite was written to show how I intend to use the library. For other examples, use Github search.

https://github.com/search?p=3&q=dbus-next+language%3AJavaScript+language%3ATypeScript&type=Code
